# Generated by Django 2.2.10 on 2021-02-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
