# Generated by Django 2.2.10 on 2021-02-16 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_printer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
