# Generated by Django 2.2.10 on 2021-02-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_delete_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('recent_work', models.TextField(blank=True, null=True)),
                ('nozzle_temperature', models.FloatField(blank=True, null=True)),
                ('time_left', models.TextField(blank=True, null=True)),
                ('time_elapsed', models.TextField(blank=True, null=True)),
                ('subject_name', models.TextField(blank=True, null=True)),
                ('device_name', models.TextField(blank=True, null=True)),
                ('ip_port', models.TextField(blank=True, null=True)),
                ('connection', models.TextField(blank=True, null=True)),
                ('device_type', models.TextField(blank=True, null=True)),
                ('gcode_file', models.TextField(blank=True, null=True)),
                ('percentage', models.TextField(blank=True, null=True)),
                ('bed_temperature', models.FloatField(blank=True, null=True)),
                ('time_total', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Printer',
                'managed': False,
            },
        ),
    ]
